version: '3.7'
services:
  solr1:
    image: solr:8.4
    container_name: solr1
    ports:
     - "8981:8983"
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    volumes:
      - ./webdefault.xml:/opt/solr/server/etc/webdefault.xml
      - ./webdefault.xml:/opt/solr-8.4.1/server/etc/webdefault.xml
    networks:
      eda:
        ipv4_address: 172.16.1.6
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  solr2:
    image: solr:8.4
    container_name: solr2
    ports:
     - "8982:8983"
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    volumes:
      - ./webdefault.xml:/opt/solr/server/etc/webdefault.xml
      - ./webdefault.xml:/opt/solr-8.4.1/server/etc/webdefault.xml
    networks:
      eda:
        ipv4_address: 172.16.1.5
    depends_on:
      - zoo1
      - zoo2
      - zoo3
  zoo1:
    image: zookeeper:3.5
    container_name: zoo1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=172.16.1.2:2888:3888;2181 server.2=172.16.1.3:2888:3888;2181 server.3=172.16.1.4:2888:3888;2181
    networks:
      eda:
        ipv4_address: 172.16.1.2

  zoo2:
    image: zookeeper:3.5
    container_name: zoo2
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=172.16.1.2:2888:3888;2181 server.2=172.16.1.3:2888:3888;2181 server.3=172.16.1.4:2888:3888;2181
    networks:
      eda:
        ipv4_address: 172.16.1.3

  zoo3:
    image: zookeeper:3.5
    container_name: zoo3
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=172.16.1.2:2888:3888;2181 server.2=172.16.1.3:2888:3888;2181 server.3=172.16.1.4:2888:3888;2181
    networks:
      eda:
        ipv4_address: 172.16.1.4

networks:
  eda:
    ipam:
      driver: default
      config:
        - subnet:  172.16.1.0/27

